//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaiTer.ATE.StringResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaiTer.ATE.StringResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 12V过压状态 的本地化字符串。
        /// </summary>
        public static string _12V过压状态 {
            get {
                return ResourceManager.GetString("12V过压状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 24V过压状态 的本地化字符串。
        /// </summary>
        public static string _24V过压状态 {
            get {
                return ResourceManager.GetString("24V过压状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ABC三相切换 的本地化字符串。
        /// </summary>
        public static string ABC三相切换 {
            get {
                return ResourceManager.GetString("ABC三相切换", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BMS需求电压(V) 的本地化字符串。
        /// </summary>
        public static string BMS需求电压_V_ {
            get {
                return ResourceManager.GetString("BMS需求电压(V)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CC1电压 的本地化字符串。
        /// </summary>
        public static string CC1电压 {
            get {
                return ResourceManager.GetString("CC1电压", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CC2电压 的本地化字符串。
        /// </summary>
        public static string CC2电压 {
            get {
                return ResourceManager.GetString("CC2电压", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CP占空比 的本地化字符串。
        /// </summary>
        public static string CP占空比 {
            get {
                return ResourceManager.GetString("CP占空比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CP电压 的本地化字符串。
        /// </summary>
        public static string CP电压 {
            get {
                return ResourceManager.GetString("CP电压", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CP频率 的本地化字符串。
        /// </summary>
        public static string CP频率 {
            get {
                return ResourceManager.GetString("CP频率", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备操控 的本地化字符串。
        /// </summary>
        public static string FrmEquipOperate {
            get {
                return ResourceManager.GetString("FrmEquipOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GDM万用表 的本地化字符串。
        /// </summary>
        public static string GDM万用表 {
            get {
                return ResourceManager.GetString("GDM万用表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 K1K2外侧电压(V) 的本地化字符串。
        /// </summary>
        public static string K1K2外侧电压_V_ {
            get {
                return ResourceManager.GetString("K1K2外侧电压(V)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待测枪信息 的本地化字符串。
        /// </summary>
        public static string lab_Left2Caption {
            get {
                return ResourceManager.GetString("lab_Left2Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测项目 的本地化字符串。
        /// </summary>
        public static string lab_Left3Caption {
            get {
                return ResourceManager.GetString("lab_Left3Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测数据 的本地化字符串。
        /// </summary>
        public static string lab_MainCaption {
            get {
                return ResourceManager.GetString("lab_MainCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接状态 的本地化字符串。
        /// </summary>
        public static string lab_Right3Caption {
            get {
                return ResourceManager.GetString("lab_Right3Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户身份 的本地化字符串。
        /// </summary>
        public static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备实时状态监控 的本地化字符串。
        /// </summary>
        public static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行状态 的本地化字符串。
        /// </summary>
        public static string lblLog {
            get {
                return ResourceManager.GetString("lblLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProxDetect 的本地化字符串。
        /// </summary>
        public static string ProxDetect {
            get {
                return ResourceManager.GetString("ProxDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S1开关状态 的本地化字符串。
        /// </summary>
        public static string S1开关状态 {
            get {
                return ResourceManager.GetString("S1开关状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S2开关状态 的本地化字符串。
        /// </summary>
        public static string S2开关状态 {
            get {
                return ResourceManager.GetString("S2开关状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S3开关状态 的本地化字符串。
        /// </summary>
        public static string S3开关状态 {
            get {
                return ResourceManager.GetString("S3开关状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Signal d1 的本地化字符串。
        /// </summary>
        public static string Signal_d1 {
            get {
                return ResourceManager.GetString("Signal d1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Signal d2 的本地化字符串。
        /// </summary>
        public static string Signal_d2 {
            get {
                return ResourceManager.GetString("Signal d2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Signal k 的本地化字符串。
        /// </summary>
        public static string Signal_k {
            get {
                return ResourceManager.GetString("Signal k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充电枪录入 的本地化字符串。
        /// </summary>
        public static string tsBtnAddChargeInfo {
            get {
                return ResourceManager.GetString("tsBtnAddChargeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动检测 的本地化字符串。
        /// </summary>
        public static string tsBtnAuto {
            get {
                return ResourceManager.GetString("tsBtnAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CAN报文 的本地化字符串。
        /// </summary>
        public static string tsBtnCAN {
            get {
                return ResourceManager.GetString("tsBtnCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑方案 的本地化字符串。
        /// </summary>
        public static string tsBtnEditScheme {
            get {
                return ResourceManager.GetString("tsBtnEditScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备操作 的本地化字符串。
        /// </summary>
        public static string tsBtnEquipOperate {
            get {
                return ResourceManager.GetString("tsBtnEquipOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MES设置 的本地化字符串。
        /// </summary>
        public static string tsBtnMESSet {
            get {
                return ResourceManager.GetString("tsBtnMESSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信设置 的本地化字符串。
        /// </summary>
        public static string tsBtnPortSet {
            get {
                return ResourceManager.GetString("tsBtnPortSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        public static string tsBtnRegist {
            get {
                return ResourceManager.GetString("tsBtnRegist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存数据 的本地化字符串。
        /// </summary>
        public static string tsBtnSaveData {
            get {
                return ResourceManager.GetString("tsBtnSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方案选择 的本地化字符串。
        /// </summary>
        public static string tsBtnSchemeSelect {
            get {
                return ResourceManager.GetString("tsBtnSchemeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备配置 的本地化字符串。
        /// </summary>
        public static string tsBtnSysParam {
            get {
                return ResourceManager.GetString("tsBtnSysParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出报告 的本地化字符串。
        /// </summary>
        public static string tsBtnTrialData {
            get {
                return ResourceManager.GetString("tsBtnTrialData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始检测 的本地化字符串。
        /// </summary>
        public static string tsBtnTrialStart {
            get {
                return ResourceManager.GetString("tsBtnTrialStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止检测 的本地化字符串。
        /// </summary>
        public static string tsBtnTrialStop {
            get {
                return ResourceManager.GetString("tsBtnTrialStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        public static string tsBtnUser {
            get {
                return ResourceManager.GetString("tsBtnUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选中所有测试项目 的本地化字符串。
        /// </summary>
        public static string ucChargerInfo_chbAllTestItems {
            get {
                return ResourceManager.GetString("ucChargerInfo.chbAllTestItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 枪号 的本地化字符串。
        /// </summary>
        public static string ucChargerInfo_chbCharger1 {
            get {
                return ResourceManager.GetString("ucChargerInfo.chbCharger1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波特率/IP 的本地化字符串。
        /// </summary>
        public static string ucConnectState_clmBaudRate {
            get {
                return ResourceManager.GetString("ucConnectState.clmBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口号 的本地化字符串。
        /// </summary>
        public static string ucConnectState_clmCom {
            get {
                return ResourceManager.GetString("ucConnectState.clmCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备名 的本地化字符串。
        /// </summary>
        public static string ucConnectState_clmName {
            get {
                return ResourceManager.GetString("ucConnectState.clmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总结论 的本地化字符串。
        /// </summary>
        public static string ucLog_label2 {
            get {
                return ResourceManager.GetString("ucLog.label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ZJ剩余电流保护测试仪 的本地化字符串。
        /// </summary>
        public static string ZJ剩余电流保护测试仪 {
            get {
                return ResourceManager.GetString("ZJ剩余电流保护测试仪", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ΣA组三相功率因数 的本地化字符串。
        /// </summary>
        public static string ΣA组三相功率因数 {
            get {
                return ResourceManager.GetString("ΣA组三相功率因数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ΣA组三相总功率(kW) 的本地化字符串。
        /// </summary>
        public static string ΣA组三相总功率_kW_ {
            get {
                return ResourceManager.GetString("ΣA组三相总功率(kW)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ΣA组三相总电压值(V) 的本地化字符串。
        /// </summary>
        public static string ΣA组三相总电压值_V_ {
            get {
                return ResourceManager.GetString("ΣA组三相总电压值(V)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ΣA组三相总电流值(V) 的本地化字符串。
        /// </summary>
        public static string ΣA组三相总电流值_V_ {
            get {
                return ResourceManager.GetString("ΣA组三相总电流值(V)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 万用表 的本地化字符串。
        /// </summary>
        public static string 万用表 {
            get {
                return ResourceManager.GetString("万用表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上限 的本地化字符串。
        /// </summary>
        public static string 上限 {
            get {
                return ResourceManager.GetString("上限", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下限 的本地化字符串。
        /// </summary>
        public static string 下限 {
            get {
                return ResourceManager.GetString("下限", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交流 的本地化字符串。
        /// </summary>
        public static string 交流 {
            get {
                return ResourceManager.GetString("交流", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交流回馈负载 的本地化字符串。
        /// </summary>
        public static string 交流回馈负载 {
            get {
                return ResourceManager.GetString("交流回馈负载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交流导引BMS 的本地化字符串。
        /// </summary>
        public static string 交流导引BMS {
            get {
                return ResourceManager.GetString("交流导引BMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交流源 的本地化字符串。
        /// </summary>
        public static string 交流源 {
            get {
                return ResourceManager.GetString("交流源", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交流电阻负载 的本地化字符串。
        /// </summary>
        public static string 交流电阻负载 {
            get {
                return ResourceManager.GetString("交流电阻负载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供电电压(V) 的本地化字符串。
        /// </summary>
        public static string 供电电压_V_ {
            get {
                return ResourceManager.GetString("供电电压(V)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供电电流(A) 的本地化字符串。
        /// </summary>
        public static string 供电电流_A_ {
            get {
                return ResourceManager.GetString("供电电流(A)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供电频率(Hz) 的本地化字符串。
        /// </summary>
        public static string 供电频率_Hz_ {
            get {
                return ResourceManager.GetString("供电频率(Hz)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存数据会封存当前枪信息的所有检测数据，\r\n保存成功后需要重新录入枪信息，是否需要保存？ 的本地化字符串。
        /// </summary>
        public static string 保存数据会封存当前枪信息的所有检测数据 {
            get {
                return ResourceManager.GetString("保存数据会封存当前枪信息的所有检测数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许充电电流 的本地化字符串。
        /// </summary>
        public static string 允许充电电流 {
            get {
                return ResourceManager.GetString("允许充电电流", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充电功率 的本地化字符串。
        /// </summary>
        public static string 充电功率 {
            get {
                return ResourceManager.GetString("充电功率", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充电桩模拟器 的本地化字符串。
        /// </summary>
        public static string 充电桩模拟器 {
            get {
                return ResourceManager.GetString("充电桩模拟器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充电状态 的本地化字符串。
        /// </summary>
        public static string 充电状态 {
            get {
                return ResourceManager.GetString("充电状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充电电压 的本地化字符串。
        /// </summary>
        public static string 充电电压 {
            get {
                return ResourceManager.GetString("充电电压", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充电电流 的本地化字符串。
        /// </summary>
        public static string 充电电流 {
            get {
                return ResourceManager.GetString("充电电流", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充电电量 的本地化字符串。
        /// </summary>
        public static string 充电电量 {
            get {
                return ResourceManager.GetString("充电电量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余电流保护测试仪 的本地化字符串。
        /// </summary>
        public static string 剩余电流保护测试仪 {
            get {
                return ResourceManager.GetString("剩余电流保护测试仪", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功率 的本地化字符串。
        /// </summary>
        public static string 功率 {
            get {
                return ResourceManager.GetString("功率", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功率分析仪 的本地化字符串。
        /// </summary>
        public static string 功率分析仪 {
            get {
                return ResourceManager.GetString("功率分析仪", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功率因数 的本地化字符串。
        /// </summary>
        public static string 功率因数 {
            get {
                return ResourceManager.GetString("功率因数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 占空比 的本地化字符串。
        /// </summary>
        public static string 占空比 {
            get {
                return ResourceManager.GetString("占空比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 号枪 的本地化字符串。
        /// </summary>
        public static string 号枪 {
            get {
                return ResourceManager.GetString("号枪", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 号枪互操作 的本地化字符串。
        /// </summary>
        public static string 号枪互操作 {
            get {
                return ResourceManager.GetString("号枪互操作", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 号枪位示波器截图 的本地化字符串。
        /// </summary>
        public static string 号枪位示波器截图 {
            get {
                return ResourceManager.GetString("号枪位示波器截图", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回馈负载 的本地化字符串。
        /// </summary>
        public static string 回馈负载 {
            get {
                return ResourceManager.GetString("回馈负载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国标 的本地化字符串。
        /// </summary>
        public static string 国标 {
            get {
                return ResourceManager.GetString("国标", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国标直流导引BMS 的本地化字符串。
        /// </summary>
        public static string 国标直流导引BMS {
            get {
                return ResourceManager.GetString("国标直流导引BMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线设备(台) 的本地化字符串。
        /// </summary>
        public static string 在线设备_台_ {
            get {
                return ResourceManager.GetString("在线设备(台)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多通道交流 的本地化字符串。
        /// </summary>
        public static string 多通道交流 {
            get {
                return ResourceManager.GetString("多通道交流", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多通道直流 的本地化字符串。
        /// </summary>
        public static string 多通道直流 {
            get {
                return ResourceManager.GetString("多通道直流", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安规 的本地化字符串。
        /// </summary>
        public static string 安规 {
            get {
                return ResourceManager.GetString("安规", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实时电压(V) 的本地化字符串。
        /// </summary>
        public static string 实时电压_V_ {
            get {
                return ResourceManager.GetString("实时电压(V)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实时电流(mA) 的本地化字符串。
        /// </summary>
        public static string 实时电流_mA_ {
            get {
                return ResourceManager.GetString("实时电流(mA)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实际 的本地化字符串。
        /// </summary>
        public static string 实际 {
            get {
                return ResourceManager.GetString("实际", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前测试开始时间 的本地化字符串。
        /// </summary>
        public static string 当前测试开始时间 {
            get {
                return ResourceManager.GetString("当前测试开始时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前测试结束时间 的本地化字符串。
        /// </summary>
        public static string 当前测试结束时间 {
            get {
                return ResourceManager.GetString("当前测试结束时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前测试耗时 的本地化字符串。
        /// </summary>
        public static string 当前测试耗时 {
            get {
                return ResourceManager.GetString("当前测试耗时", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当日不合格桩数量 的本地化字符串。
        /// </summary>
        public static string 当日不合格桩数量 {
            get {
                return ResourceManager.GetString("当日不合格桩数量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当日合格桩数量 的本地化字符串。
        /// </summary>
        public static string 当日合格桩数量 {
            get {
                return ResourceManager.GetString("当日合格桩数量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当日合格率(%) 的本地化字符串。
        /// </summary>
        public static string 当日合格率___ {
            get {
                return ResourceManager.GetString("当日合格率(%)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当日测试桩总数量 的本地化字符串。
        /// </summary>
        public static string 当日测试桩总数量 {
            get {
                return ResourceManager.GetString("当日测试桩总数量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录波板 的本地化字符串。
        /// </summary>
        public static string 录波板 {
            get {
                return ResourceManager.GetString("录波板", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待测... 的本地化字符串。
        /// </summary>
        public static string 待测___ {
            get {
                return ResourceManager.GetString("待测...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截图 的本地化字符串。
        /// </summary>
        public static string 截图 {
            get {
                return ResourceManager.GetString("截图", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有充电桩未做任何测试无法保存 的本地化字符串。
        /// </summary>
        public static string 所有充电桩未做任何测试无法保存 {
            get {
                return ResourceManager.GetString("所有充电桩未做任何测试无法保存", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报文 的本地化字符串。
        /// </summary>
        public static string 报文 {
            get {
                return ResourceManager.GetString("报文", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表 的本地化字符串。
        /// </summary>
        public static string 报表 {
            get {
                return ResourceManager.GetString("报表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表(勿删) 的本地化字符串。
        /// </summary>
        public static string 报表_勿删_ {
            get {
                return ResourceManager.GetString("报表(勿删)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警显示 的本地化字符串。
        /// </summary>
        public static string 报警显示 {
            get {
                return ResourceManager.GetString("报警显示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string 提示 {
            get {
                return ResourceManager.GetString("提示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作状态 的本地化字符串。
        /// </summary>
        public static string 操作状态 {
            get {
                return ResourceManager.GetString("操作状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 效率值 的本地化字符串。
        /// </summary>
        public static string 效率值 {
            get {
                return ResourceManager.GetString("效率值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据保存失败 的本地化字符串。
        /// </summary>
        public static string 数据保存失败 {
            get {
                return ResourceManager.GetString("数据保存失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据保存成功，当前枪信息已删除，请重新录入桩信息 的本地化字符串。
        /// </summary>
        public static string 数据保存成功当前枪信息已删除请重新录入桩信息 {
            get {
                return ResourceManager.GetString("数据保存成功当前枪信息已删除请重新录入桩信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据项 的本地化字符串。
        /// </summary>
        public static string 数据项 {
            get {
                return ResourceManager.GetString("数据项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 施加漏电测脱扣时间 的本地化字符串。
        /// </summary>
        public static string 施加漏电测脱扣时间 {
            get {
                return ResourceManager.GetString("施加漏电测脱扣时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 施加漏电测脱扣电流 的本地化字符串。
        /// </summary>
        public static string 施加漏电测脱扣电流 {
            get {
                return ResourceManager.GetString("施加漏电测脱扣电流", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日标 的本地化字符串。
        /// </summary>
        public static string 日标 {
            get {
                return ResourceManager.GetString("日标", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日标直流导引BMS 的本地化字符串。
        /// </summary>
        public static string 日标直流导引BMS {
            get {
                return ResourceManager.GetString("日标直流导引BMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大功率(kW) 的本地化字符串。
        /// </summary>
        public static string 最大功率_kW_ {
            get {
                return ResourceManager.GetString("最大功率(kW)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有充电桩未做任何测试.无法保存 的本地化字符串。
        /// </summary>
        public static string 有充电桩未做任何测试_无法保存 {
            get {
                return ResourceManager.GetString("有充电桩未做任何测试.无法保存", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未脱扣 的本地化字符串。
        /// </summary>
        public static string 未脱扣 {
            get {
                return ResourceManager.GetString("未脱扣", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 枪 的本地化字符串。
        /// </summary>
        public static string 枪 {
            get {
                return ResourceManager.GetString("枪", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 枪号 的本地化字符串。
        /// </summary>
        public static string 枪号 {
            get {
                return ResourceManager.GetString("枪号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 枪座温度 的本地化字符串。
        /// </summary>
        public static string 枪座温度 {
            get {
                return ResourceManager.GetString("枪座温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 枪连接状态 的本地化字符串。
        /// </summary>
        public static string 枪连接状态 {
            get {
                return ResourceManager.GetString("枪连接状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看录波截图 的本地化字符串。
        /// </summary>
        public static string 查看录波截图 {
            get {
                return ResourceManager.GetString("查看录波截图", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看示波器截图 的本地化字符串。
        /// </summary>
        public static string 查看示波器截图 {
            get {
                return ResourceManager.GetString("查看示波器截图", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检定项 的本地化字符串。
        /// </summary>
        public static string 检定项 {
            get {
                return ResourceManager.GetString("检定项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试中 的本地化字符串。
        /// </summary>
        public static string 检测中 {
            get {
                return ResourceManager.GetString("检测中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测刷卡上电状态 的本地化字符串。
        /// </summary>
        public static string 检测刷卡上电状态 {
            get {
                return ResourceManager.GetString("检测刷卡上电状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测方案 的本地化字符串。
        /// </summary>
        public static string 检测方案 {
            get {
                return ResourceManager.GetString("检测方案", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测系统开启，处于空闲状态 的本地化字符串。
        /// </summary>
        public static string 检测系统开启处于空闲状态 {
            get {
                return ResourceManager.GetString("检测系统开启处于空闲状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测结果 的本地化字符串。
        /// </summary>
        public static string 检测结果 {
            get {
                return ResourceManager.GetString("检测结果", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欧标 的本地化字符串。
        /// </summary>
        public static string 欧标 {
            get {
                return ResourceManager.GetString("欧标", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欧标直流导引BMS 的本地化字符串。
        /// </summary>
        public static string 欧标直流导引BMS {
            get {
                return ResourceManager.GetString("欧标直流导引BMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测动作时间(ms) 的本地化字符串。
        /// </summary>
        public static string 测动作时间 {
            get {
                return ResourceManager.GetString("测动作时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测动作电流(mA) 的本地化字符串。
        /// </summary>
        public static string 测动作电流 {
            get {
                return ResourceManager.GetString("测动作电流", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试时间(ms) 的本地化字符串。
        /// </summary>
        public static string 测试时间_mS_ {
            get {
                return ResourceManager.GetString("测试时间(mS)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试电流(mA) 的本地化字符串。
        /// </summary>
        public static string 测试电流_mA_ {
            get {
                return ResourceManager.GetString("测试电流(mA)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试结果 的本地化字符串。
        /// </summary>
        public static string 测试结果 {
            get {
                return ResourceManager.GetString("测试结果", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量值 的本地化字符串。
        /// </summary>
        public static string 测量值 {
            get {
                return ResourceManager.GetString("测量值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本号 的本地化字符串。
        /// </summary>
        public static string 版本号 {
            get {
                return ResourceManager.GetString("版本号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string 状态 {
            get {
                return ResourceManager.GetString("状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 环境温度 的本地化字符串。
        /// </summary>
        public static string 环境温度 {
            get {
                return ResourceManager.GetString("环境温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名和密码不能为空 的本地化字符串。
        /// </summary>
        public static string 用户名和密码不能为空 {
            get {
                return ResourceManager.GetString("用户名和密码不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或密码不正确 的本地化字符串。
        /// </summary>
        public static string 用户名或密码不正确 {
            get {
                return ResourceManager.GetString("用户名或密码不正确", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电压 的本地化字符串。
        /// </summary>
        public static string 电压 {
            get {
                return ResourceManager.GetString("电压", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子负载 的本地化字符串。
        /// </summary>
        public static string 电子负载 {
            get {
                return ResourceManager.GetString("电子负载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电流 的本地化字符串。
        /// </summary>
        public static string 电流 {
            get {
                return ResourceManager.GetString("电流", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电表 的本地化字符串。
        /// </summary>
        public static string 电表 {
            get {
                return ResourceManager.GetString("电表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电阻 的本地化字符串。
        /// </summary>
        public static string 电阻 {
            get {
                return ResourceManager.GetString("电阻", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电阻负载 的本地化字符串。
        /// </summary>
        public static string 电阻负载 {
            get {
                return ResourceManager.GetString("电阻负载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录成功 的本地化字符串。
        /// </summary>
        public static string 登录成功 {
            get {
                return ResourceManager.GetString("登录成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直流 的本地化字符串。
        /// </summary>
        public static string 直流 {
            get {
                return ResourceManager.GetString("直流", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直流导引BMS 的本地化字符串。
        /// </summary>
        public static string 直流导引BMS {
            get {
                return ResourceManager.GetString("直流导引BMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直流电阻负载 的本地化字符串。
        /// </summary>
        public static string 直流电阻负载 {
            get {
                return ResourceManager.GetString("直流电阻负载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 示波器 的本地化字符串。
        /// </summary>
        public static string 示波器 {
            get {
                return ResourceManager.GetString("示波器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程控板 的本地化字符串。
        /// </summary>
        public static string 程控板 {
            get {
                return ResourceManager.GetString("程控板", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员 的本地化字符串。
        /// </summary>
        public static string 管理员 {
            get {
                return ResourceManager.GetString("管理员", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统状态 的本地化字符串。
        /// </summary>
        public static string 系统状态 {
            get {
                return ResourceManager.GetString("系统状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继电器 的本地化字符串。
        /// </summary>
        public static string 继电器 {
            get {
                return ResourceManager.GetString("继电器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 美标 的本地化字符串。
        /// </summary>
        public static string 美标 {
            get {
                return ResourceManager.GetString("美标", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 美标直流导引BMS 的本地化字符串。
        /// </summary>
        public static string 美标直流导引BMS {
            get {
                return ResourceManager.GetString("美标直流导引BMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超级管理员 的本地化字符串。
        /// </summary>
        public static string 超级管理员 {
            get {
                return ResourceManager.GetString("超级管理员", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 辅助电源电压 的本地化字符串。
        /// </summary>
        public static string 辅助电源电压 {
            get {
                return ResourceManager.GetString("辅助电源电压", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 辅源电流(A) 的本地化字符串。
        /// </summary>
        public static string 辅源电流_A_ {
            get {
                return ResourceManager.GetString("辅源电流(A)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 辅源短路状态 的本地化字符串。
        /// </summary>
        public static string 辅源短路状态 {
            get {
                return ResourceManager.GetString("辅源短路状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 辅源负载 的本地化字符串。
        /// </summary>
        public static string 辅源负载 {
            get {
                return ResourceManager.GetString("辅源负载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入功率值(W) 的本地化字符串。
        /// </summary>
        public static string 输入功率值_W_ {
            get {
                return ResourceManager.GetString("输入功率值(W)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入电压值(V) 的本地化字符串。
        /// </summary>
        public static string 输入电压值_V_ {
            get {
                return ResourceManager.GetString("输入电压值(V)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入电流值(A) 的本地化字符串。
        /// </summary>
        public static string 输入电流值_A_ {
            get {
                return ResourceManager.GetString("输入电流值(A)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出电压(V) 的本地化字符串。
        /// </summary>
        public static string 输出电压_V_ {
            get {
                return ResourceManager.GetString("输出电压(V)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过压参考值(V) 的本地化字符串。
        /// </summary>
        public static string 过压参考值_V_ {
            get {
                return ResourceManager.GetString("过压参考值(V)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行状态 的本地化字符串。
        /// </summary>
        public static string 运行状态 {
            get {
                return ResourceManager.GetString("运行状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通道 的本地化字符串。
        /// </summary>
        public static string 通道 {
            get {
                return ResourceManager.GetString("通道", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通道{0} 功率(kW) 的本地化字符串。
        /// </summary>
        public static string 通道_0__功率_kW_ {
            get {
                return ResourceManager.GetString("通道{0} 功率(kW)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通道{0} 功率因数 的本地化字符串。
        /// </summary>
        public static string 通道_0__功率因数 {
            get {
                return ResourceManager.GetString("通道{0} 功率因数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通道{0} 均方根电压(V) 的本地化字符串。
        /// </summary>
        public static string 通道_0__均方根电压_V_ {
            get {
                return ResourceManager.GetString("通道{0} 均方根电压(V)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通道{0} 均方根电流(A) 的本地化字符串。
        /// </summary>
        public static string 通道_0__均方根电流_A_ {
            get {
                return ResourceManager.GetString("通道{0} 均方根电流(A)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通道{0} 无功功率(Var) 的本地化字符串。
        /// </summary>
        public static string 通道_0__无功功率_Var_ {
            get {
                return ResourceManager.GetString("通道{0} 无功功率(Var)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新注册 的本地化字符串。
        /// </summary>
        public static string 重新注册 {
            get {
                return ResourceManager.GetString("重新注册", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误信息 的本地化字符串。
        /// </summary>
        public static string 错误信息 {
            get {
                return ResourceManager.GetString("错误信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需求 的本地化字符串。
        /// </summary>
        public static string 需求 {
            get {
                return ResourceManager.GetString("需求", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预先调整动作电流 的本地化字符串。
        /// </summary>
        public static string 预先调整动作电流 {
            get {
                return ResourceManager.GetString("预先调整动作电流", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频率 的本地化字符串。
        /// </summary>
        public static string 频率 {
            get {
                return ResourceManager.GetString("频率", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 额定电流(A) 的本地化字符串。
        /// </summary>
        public static string 额定电流_A_ {
            get {
                return ResourceManager.GetString("额定电流(A)", resourceCulture);
            }
        }
    }
}
